[build]
  command = "npm install"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
